### ISSUE TITLE
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException

### ISSUE THREAD

**Issue by AdrianSimionov** [ThibautSF/ParadoxosModManagerRework#37]
Following error generated when trying to apply the settings on OSX.

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.pmm.ParadoxosGameModManager/com.pmm.ParadoxosGameModManager.ListManager.applyOneModListV2(Unknown Source)
	at com.pmm.ParadoxosGameModManager/com.pmm.ParadoxosGameModManager.ListManager.applyModList(Unknown Source)
	at com.pmm.ParadoxosGameModManager/com.pmm.ParadoxosGameModManager.ListManager$8.handle(Unknown Source)
	at com.pmm.ParadoxosGameModManager/com.pmm.ParadoxosGameModManager.ListManager$8.handle(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Node.fireEvent(Unknown Source)
	at javafx.controls/javafx.scene.control.Button.fire(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.mac.MacView.notifyMouse(Unknown Source)
```

**Comment by ThibautSF** [comment]
Do you use 0.8.2 or latest indev build?

**Comment by AdrianSimionov** [comment]
0.8.2

**Comment by ThibautSF** [comment]
You answer faster than I edit the message ^^

"If you don't use indev, could you try it and reproduce the same manipulations to see if it works or if it's still generating an error."

https://github.com/ThibautSF/ParadoxosModManagerRework/releases/tag/indev

**Comment by ThibautSF** [comment]
I'm asking that because I've got someone on the forum which reports a similar bug.
I added more error catching (in order to write it in DebugLog file) and looks like I also change a line which solved the problem.
![image](https://user-images.githubusercontent.com/9386581/85016300-c3a0d000-b169-11ea-8535-46119f683988.png)

**Comment by AdrianSimionov** [comment]
Do you have nightly builds somewhere? More than happy to try a Dev build, I am on OSX Catalina.

**Comment by AdrianSimionov** [comment]
OK, So it does work, once I manually create all 3 JSON files and added 1 mod by hand.

I think the fix would be to create all 3 JSON files if they do not exist and populate it:
dlc_load.json
game_data.json
mods_registry.json

The whole idea of using this Mods Manager was for the corner case when the game is not launched via Steam.

**Comment by ThibautSF** [comment]
I will note that.

The only needed file by PMM is dlc_load.json

A normal use is to execute the launcher and activate one mod with it (no need to start the game) and it should create all needed files.

**Comment by ThibautSF** [comment]
For dev builds, there is an indev tag in releases which contain the latest build each time I push the tag (which I usually push each commit which add a functionality I consider functional). 

You can also look the readme.md and build from source.
(you should just need to download and install a JDK 11 and set java home)

**Comment by AdrianSimionov** [comment]
The problem is the Launcher does not work for Stellaris on OSX. Only the game.
