### ISSUE TITLE
Java error on mac?

### ISSUE THREAD

**Issue by JenkoRun** [ThibautSF/ParadoxosModManagerRework#45]
Hi, I'm trying to run V8.2 on a mac version 10.13 and I get this error in the terminal when trying to launch the unix file:

Exception in Application start method
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: supported_games.json (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(Unknown Source)
	at java.base/java.io.FileInputStream.<init>(Unknown Source)
	at java.base/java.io.FileReader.<init>(Unknown Source)
	at com.pmm.ParadoxosGameModManager/com.pmm.ParadoxosGameModManager.ModManager.start(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
Exception running application com.pmm.ParadoxosGameModManager.ModManager
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by ThibautSF** [comment]
> Hi, I'm trying to run V8.2 on a mac version 10.13 and I get this error in the terminal when trying to launch the unix file:
> 
> ...
> Caused by: java.io.FileNotFoundException: supported_games.json (No such file or directory)

Are you sure that you got the program from the [releases page](https://github.com/ThibautSF/ParadoxosModManagerRework/releases)?
You can take the "Indev" version: https://github.com/ThibautSF/ParadoxosModManagerRework/releases/tag/indev

The root folder should be a bit like this one : 
![image](https://user-images.githubusercontent.com/9386581/92590195-176c1280-f29c-11ea-84bb-dec91b44ffc7.png)
(Note: I don't have Mac, so here is a Windows one, just ignore .bat and .exe, use the launch script)

**Comment by JenkoRun** [comment]
> > Hi, I'm trying to run V8.2 on a mac version 10.13 and I get this error in the terminal when trying to launch the unix file:
> > ...
> > Caused by: java.io.FileNotFoundException: supported_games.json (No such file or directory)
> 
> Are you sure that you got the program from the [releases page](https://github.com/ThibautSF/ParadoxosModManagerRework/releases)?
> You can take the "Indev" version: https://github.com/ThibautSF/ParadoxosModManagerRework/releases/tag/indev
> 
> The root folder should be a bit like this one :
> ![image](https://user-images.githubusercontent.com/9386581/92590195-176c1280-f29c-11ea-84bb-dec91b44ffc7.png)
> (Note: I don't have Mac, so here is a Windows one, just ignore .bat and .exe, use the launch script)

No luck, same error.

**Comment by ThibautSF** [comment]
Could you try to move the file "supported_games.json" in "bin/" folder?

**Comment by JenkoRun** [comment]
> Could you try to move the file "supported_games.json" in "bin/" folder?

Same error, sorry

**Comment by ThibautSF** [comment]
For now, the only origin I can find for this error is that the working dir isn't correct...

**Comment by sord33** [comment]
I'm having the same issue as well, with the same details but on macOS 10.15.7.

**Comment by ThibautSF** [comment]
Looks like that the unix script doesn't change well the working repository 🤔
I'm not able to really helps you since I don't own a mac...

A workaround could be to build from source : 
https://github.com/ThibautSF/ParadoxosModManagerRework#build-latest-from-source

You will need to install full java 11 jdk and write 2 commands.

**Comment by sord33** [comment]
I can run the program from the source code using ./gradlew run but once I build it the program stops working.
